### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by aschrijver** [commanded/generator#3]
Hi @slashdotdash 

Thank you for providing the source of this project. I think that the idea to make this public was for others to use it. However, there is no license and the project is de-facto proprietary, copyright all rights reserved. Could you indicate if that is intentional, and otherwise add a license under which other people can reuse the code?

**Comment by slashdotdash** [comment]
I've now added the MIT license.

**Comment by aschrijver** [comment]
Thank you!
